# Schema for the configuration files of the Next.js Site Path Alias module.
next_path_alias.settings:
  type: config_object
  label: 'Next.js Site Path Alias settings'
  mapping:
    sites_field_name:
      type: string
      label: 'Sites field name'
